//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication1.Models;

namespace WebApplication3.Models
{
    public class Messages
    {
        public IEnumerable<Table> GetMessages(MessagesDatabaseEntities db)
        {
            try
            {
                if (db != null)
                {
                    return db.Table.ToList();
                }
                return null;
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}